<a href="https://colab.research.google.com/github/brendharosa/primeiro1/blob/main/Projeto_Pr%C3%A1tico_Individual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Análise do Perfil dos Candidatos do Rio Grende do Sul nas Eleições Municipais de 2024**
Este trabalho tem como objetivo realizar uma análise dos dados dos candidatos do Rio Grande do Sul nas eleições municipais de 2024.

A análise será desenvolvida utilizando a linguagem de Python e bibliotecas voltadas para munipulação a análise de dados. Serão analisadas informações como idade, sexo, escolaridade, cargo disputado, partido e município dos candidatos.

O objetivo é identificar as principais características do perfil dos candidatos e transformar os dados disponíveis em informações mais fáceis de compreender.

In [20]:
# Importa a biblioteca Pandas para trabalhar com os dados
import pandas as pd

In [23]:
# Lê o arquivo CSV com os dados dos candidatos do Rio Grande do Sul
dados = pd.read_csv("consulta_cand_2024_RS.csv", sep=";", encoding="latin1")

# Mostra as cinco primeiras linhas do conjunto de dados
dados.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
0,07/10/2026,02:16:02,2024,1,ELEIÇÃO SUPLEMENTAR,1,6268,Eleição Suplementar Cachoeirinha - RS,12/04/2026,MUNICIPAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,278,VEREADOR,4,NÃO ELEITO
1,07/10/2026,02:16:02,2024,1,ELEIÇÃO SUPLEMENTAR,1,6268,Eleição Suplementar Cachoeirinha - RS,12/04/2026,MUNICIPAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",4,NÃO ELEITO
2,07/10/2026,02:16:02,2024,1,ELEIÇÃO SUPLEMENTAR,1,6268,Eleição Suplementar Cachoeirinha - RS,12/04/2026,MUNICIPAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,190,FOTÓGRAFO E ASSEMELHADOS,4,NÃO ELEITO
3,07/10/2026,02:16:02,2024,2,ELEIÇÃO ORDINÁRIA,1,619,Eleições Municipais 2024,06/10/2024,MUNICIPAL,...,6,ENSINO MÉDIO COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO
4,07/10/2026,02:16:02,2024,2,ELEIÇÃO ORDINÁRIA,1,619,Eleições Municipais 2024,06/10/2024,MUNICIPAL,...,6,ENSINO MÉDIO COMPLETO,1,SOLTEIRO(A),1,BRANCA,254,VIGILANTE,4,NÃO ELEITO

In [24]:
# Mostra a quantidade de linhas e colunas do conjunto de dados
dados.shape

(29062, 50)

In [27]:
# Mostra o nome de cada coluna em uma linha
for coluna in dados.columns:
  print(coluna)

DT_GERACAO
HH_GERACAO
ANO_ELEICAO
CD_TIPO_ELEICAO
NM_TIPO_ELEICAO
NR_TURNO
CD_ELEICAO
DS_ELEICAO
DT_ELEICAO
TP_ABRANGENCIA
SG_UF
SG_UE
NM_UE
CD_CARGO
DS_CARGO
SQ_CANDIDATO
NR_CANDIDATO
NM_CANDIDATO
NM_URNA_CANDIDATO
NM_SOCIAL_CANDIDATO
NR_CPF_CANDIDATO
DS_EMAIL
CD_SITUACAO_CANDIDATURA
DS_SITUACAO_CANDIDATURA
TP_AGREMIACAO
NR_PARTIDO
SG_PARTIDO
NM_PARTIDO
NR_FEDERACAO
NM_FEDERACAO
SG_FEDERACAO
DS_COMPOSICAO_FEDERACAO
SQ_COLIGACAO
NM_COLIGACAO
DS_COMPOSICAO_COLIGACAO
SG_UF_NASCIMENTO
DT_NASCIMENTO
NR_TITULO_ELEITORAL_CANDIDATO
CD_GENERO
DS_GENERO
CD_GRAU_INSTRUCAO
DS_GRAU_INSTRUCAO
CD_ESTADO_CIVIL
DS_ESTADO_CIVIL
CD_COR_RACA
DS_COR_RACA
CD_OCUPACAO
DS_OCUPACAO
CD_SIT_TOT_TURNO
DS_SIT_TOT_TURNO

In [28]:
# Mostra o tipo de dado de cada caluna
dados.dtypes

DT_GERACAO                       object
HH_GERACAO                       object
ANO_ELEICAO                       int64
CD_TIPO_ELEICAO                   int64
NM_TIPO_ELEICAO                  object
NR_TURNO                          int64
CD_ELEICAO                        int64
DS_ELEICAO                       object
DT_ELEICAO                       object
TP_ABRANGENCIA                   object
SG_UF                            object
SG_UE                             int64
NM_UE                            object
CD_CARGO                          int64
DS_CARGO                         object
SQ_CANDIDATO                      int64
NR_CANDIDATO                      int64
NM_CANDIDATO                     object
NM_URNA_CANDIDATO                object
NM_SOCIAL_CANDIDATO              object
NR_CPF_CANDIDATO                  int64
DS_EMAIL                         object
CD_SITUACAO_CANDIDATURA           int64
DS_SITUACAO_CANDIDATURA          object
TP_AGREMIACAO                    object
NR_PARTIDO                        int64
SG_PARTIDO                       object
NM_PARTIDO                       object
NR_FEDERACAO                      int64
NM_FEDERACAO                     object
SG_FEDERACAO                     object
DS_COMPOSICAO_FEDERACAO          object
SQ_COLIGACAO                      int64
NM_COLIGACAO                     object
DS_COMPOSICAO_COLIGACAO          object
SG_UF_NASCIMENTO                 object
DT_NASCIMENTO                    object
NR_TITULO_ELEITORAL_CANDIDATO     int64
CD_GENERO                         int64
DS_GENERO                        object
CD_GRAU_INSTRUCAO                 int64
DS_GRAU_INSTRUCAO                object
CD_ESTADO_CIVIL                   int64
DS_ESTADO_CIVIL                  object
CD_COR_RACA                       int64
DS_COR_RACA                      object
CD_OCUPACAO                       int64
DS_OCUPACAO                      object
CD_SIT_TOT_TURNO                  int64
DS_SIT_TOT_TURNO                 object
dtype: object

In [29]:
# Verifica a quantidade de valores ausentes em cada coluna
dados.isnull().sum()

DT_GERACAO                       0
HH_GERACAO                       0
ANO_ELEICAO                      0
CD_TIPO_ELEICAO                  0
NM_TIPO_ELEICAO                  0
NR_TURNO                         0
CD_ELEICAO                       0
DS_ELEICAO                       0
DT_ELEICAO                       0
TP_ABRANGENCIA                   0
SG_UF                            0
SG_UE                            0
NM_UE                            0
CD_CARGO                         0
DS_CARGO                         0
SQ_CANDIDATO                     0
NR_CANDIDATO                     0
NM_CANDIDATO                     0
NM_URNA_CANDIDATO                0
NM_SOCIAL_CANDIDATO              0
NR_CPF_CANDIDATO                 0
DS_EMAIL                         0
CD_SITUACAO_CANDIDATURA          0
DS_SITUACAO_CANDIDATURA          0
TP_AGREMIACAO                    0
NR_PARTIDO                       0
SG_PARTIDO                       0
NM_PARTIDO                       0
NR_FEDERACAO                     0
NM_FEDERACAO                     0
SG_FEDERACAO                     0
DS_COMPOSICAO_FEDERACAO          0
SQ_COLIGACAO                     0
NM_COLIGACAO                     0
DS_COMPOSICAO_COLIGACAO          0
SG_UF_NASCIMENTO                 0
DT_NASCIMENTO                    0
NR_TITULO_ELEITORAL_CANDIDATO    0
CD_GENERO                        0
DS_GENERO                        0
CD_GRAU_INSTRUCAO                0
DS_GRAU_INSTRUCAO                0
CD_ESTADO_CIVIL                  0
DS_ESTADO_CIVIL                  0
CD_COR_RACA                      0
DS_COR_RACA                      0
CD_OCUPACAO                      0
DS_OCUPACAO                      0
CD_SIT_TOT_TURNO                 0
DS_SIT_TOT_TURNO                 0
dtype: int64

In [30]:
# Guarda a quantidade de valores ausentes de cada coluna
ausentes = dados.isnull().sum()

# Mostra apenas as colunas que possuem valores ausentes
ausentes[ausentes > 0]

Series([], dtype: int64)

In [31]:
# Verifica a quantidade de registros duplicados no conjunto de dados
dados.duplicated().sum()

np.int64(0)

In [32]:
# Conta quantos candidatos existem de cada gênero
dados["DS_GENERO"].value_counts()

DS_GENERO
MASCULINO    18980
FEMININO     10082
Name: count, dtype: int64